-- add user roles
INSERT INTO `roles` (`id`, `role`, `created_at`, `updated_at`)
VALUES
 (NULL, 'Admin', NULL, NULL),
 (NULL, 'Owner', NULL, NULL),
 (NULL, 'Manager', NULL, NULL),
 (NULL, 'Accountant', NULL, NULL),
 (NULL, 'Sales Agent', NULL, NULL),
 (NULL, 'Booking Manager', NULL, NULL),
 (NULL, 'Guide', NULL, NULL),
 (NULL, 'Hotel User', NULL, NULL),
 (NULL, 'Intern', NULL, NULL);


-- add default user
INSERT INTO `users` (`id`, `first_name`, `last_name`, `phone1`, `phone2`, `email`, `email_verified_at`, `password`, `profile_picture`, `status`, `remember_token`, `created_at`, `updated_at`, `role_id`) VALUES
(1, 'Main', 'Admin', '0525094487', '0769641844', 'chinthana144@gmail.com', NULL, '$2y$12$zoSCnmKYGIJEFz6Ixa1xW.3oHBGOx2aYKe8awQamJyehsyZQQve56', 'images/profiles/profile.jpg', 1, 'A7NIo5J1keFShEjs7HTbRklqxEJb2METOGPmFaaDj4tz0QyjpLlwJo1Yfpbz', '2025-08-23 01:07:09', '2025-08-24 14:25:40', 1),
(2, 'Asela', 'Edirisinghe', '+817066471777', '0769641844', 'asela@akagiexp.com', NULL, '$2y$12$K7YDOGFS/4/qDre29euPjumJXl/Ps7bMEEHGEDnECXA9tKA/ITT62', 'images/profiles/profile.jpg', 1, 'A7NIo5J1keFShEjs7HTbRklqxEJb2METOGPmFaaDj4tz0QyjpLlwJo1Yfpbz', '2025-08-23 01:07:09', '2025-08-24 14:25:40', 1);


-- add countries
INSERT INTO `countries` (`id`, `shortname`, `name`, `phonecode`, `flag`) VALUES
(1, 'AF', 'Afghanistan', 93, 'AF.png'),
(2, 'AL', 'Albania', 355, 'AL.png'),
(3, 'DZ', 'Algeria', 213, 'DZ.png'),
(4, 'AS', 'American Samoa', 1684, 'AS.png'),
(5, 'AD', 'Andorra', 376, 'AD.png'),
(6, 'AO', 'Angola', 244, 'AO.png'),
(7, 'AI', 'Anguilla', 1264, 'AI.png'),
(8, 'AQ', 'Antarctica', 0, 'AQ.png'),
(9, 'AG', 'Antigua And Barbuda', 1268, 'AG.png'),
(10, 'AR', 'Argentina', 54, 'AR.png'),
(11, 'AM', 'Armenia', 374, 'AM.png'),
(12, 'AW', 'Aruba', 297, 'AW.png'),
(13, 'AU', 'Australia', 61, 'AU.png'),
(14, 'AT', 'Austria', 43, 'AT.png'),
(15, 'AZ', 'Azerbaijan', 994, 'AZ.png'),
(16, 'BS', 'Bahamas The', 1242, NULL),
(17, 'BH', 'Bahrain', 973, 'BH.png'),
(18, 'BD', 'Bangladesh', 880, 'BD.png'),
(19, 'BB', 'Barbados', 1246, 'BB.png'),
(20, 'BY', 'Belarus', 375, 'BY.png'),
(21, 'BE', 'Belgium', 32, 'BE.png'),
(22, 'BZ', 'Belize', 501, 'BZ.png'),
(23, 'BJ', 'Benin', 229, 'BJ.png'),
(24, 'BM', 'Bermuda', 1441, 'BM.png'),
(25, 'BT', 'Bhutan', 975, 'BT.png'),
(26, 'BO', 'Bolivia', 591, 'BO.png'),
(27, 'BA', 'Bosnia and Herzegovina', 387, 'BA.png'),
(28, 'BW', 'Botswana', 267, 'BW.png'),
(29, 'BV', 'Bouvet Island', 0, 'BV.png'),
(30, 'BR', 'Brazil', 55, 'BR.png'),
(31, 'IO', 'British Indian Ocean Territory', 246, 'IO.png'),
(32, 'BN', 'Brunei', 673, 'BN.png'),
(33, 'BG', 'Bulgaria', 359, 'BG.png'),
(34, 'BF', 'Burkina Faso', 226, 'BF.png'),
(35, 'BI', 'Burundi', 257, 'BI.png'),
(36, 'KH', 'Cambodia', 855, 'KH.png'),
(37, 'CM', 'Cameroon', 237, 'CM.png'),
(38, 'CA', 'Canada', 1, 'CA.png'),
(39, 'CV', 'Cape Verde', 238, 'CV.png'),
(40, 'KY', 'Cayman Islands', 1345, 'KY.png'),
(41, 'CF', 'Central African Republic', 236, 'CF.png'),
(42, 'TD', 'Chad', 235, 'TD.png'),
(43, 'CL', 'Chile', 56, 'CL.png'),
(44, 'CN', 'China', 86, 'CN.png'),
(45, 'CX', 'Christmas Island', 61, 'CX.png'),
(46, 'CC', 'Cocos (Keeling) Islands', 672, NULL),
(47, 'CO', 'Colombia', 57, 'CO.png'),
(48, 'KM', 'Comoros', 269, 'KM.png'),
(49, 'CG', 'Republic Of The Congo', 242, 'CG.png'),
(50, 'CD', 'Democratic Republic Of The Congo', 242, 'CD.png'),
(51, 'CK', 'Cook Islands', 682, 'CK.png'),
(52, 'CR', 'Costa Rica', 506, 'CR.png'),
(53, 'CI', 'Cote D\ Ivoire (Ivory Coast)', 225, NULL),
(54, 'HR', 'Croatia (Hrvatska)', 385, NULL),
(55, 'CU', 'Cuba', 53, 'CU.png'),
(56, 'CY', 'Cyprus', 357, 'CY.png'),
(57, 'CZ', 'Czech Republic', 420, 'CZ.png'),
(58, 'DK', 'Denmark', 45, 'DK.png'),
(59, 'DJ', 'Djibouti', 253, 'DJ.png'),
(60, 'DM', 'Dominica', 1767, 'DM.png'),
(61, 'DO', 'Dominican Republic', 1809, 'DO.png'),
(62, 'TP', 'East Timor', 670, 'TL.png'),
(63, 'EC', 'Ecuador', 593, 'EC.png'),
(64, 'EG', 'Egypt', 20, 'EG.png'),
(65, 'SV', 'El Salvador', 503, 'SV.png'),
(66, 'GQ', 'Equatorial Guinea', 240, 'GQ.png'),
(67, 'ER', 'Eritrea', 291, 'ER.png'),
(68, 'EE', 'Estonia', 372, 'EE.png'),
(69, 'ET', 'Ethiopia', 251, 'ET.png'),
(70, 'XA', 'External Territories of Australia', 61, NULL),
(71, 'FK', 'Falkland Islands', 500, 'FK.png'),
(72, 'FO', 'Faroe Islands', 298, 'FO.png'),
(73, 'FJ', 'Fiji Islands', 679, NULL),
(74, 'FI', 'Finland', 358, 'FI.png'),
(75, 'FR', 'France', 33, 'FR.png'),
(76, 'GF', 'French Guiana', 594, 'GF.png'),
(77, 'PF', 'French Polynesia', 689, 'PF.png'),
(78, 'TF', 'French Southern Territories', 0, 'TF.png'),
(79, 'GA', 'Gabon', 241, 'GA.png'),
(80, 'GM', 'Gambia The', 220, NULL),
(81, 'GE', 'Georgia', 995, 'GE.png'),
(82, 'DE', 'Germany', 49, 'DE.png'),
(83, 'GH', 'Ghana', 233, 'GH.png'),
(84, 'GI', 'Gibraltar', 350, 'GI.png'),
(85, 'GR', 'Greece', 30, 'GR.png'),
(86, 'GL', 'Greenland', 299, 'GL.png'),
(87, 'GD', 'Grenada', 1473, 'GD.png'),
(88, 'GP', 'Guadeloupe', 590, 'GP.png'),
(89, 'GU', 'Guam', 1671, 'GU.png'),
(90, 'GT', 'Guatemala', 502, 'GT.png'),
(91, 'XU', 'Guernsey and Alderney', 44, NULL),
(92, 'GN', 'Guinea', 224, 'GN.png'),
(93, 'GW', 'Guinea-Bissau', 245, 'GW.png'),
(94, 'GY', 'Guyana', 592, 'GY.png'),
(95, 'HT', 'Haiti', 509, 'HT.png'),
(96, 'HM', 'Heard and McDonald Islands', 0, NULL),
(97, 'HN', 'Honduras', 504, 'HN.png'),
(98, 'HK', 'Hong Kong S.A.R.', 852, NULL),
(99, 'HU', 'Hungary', 36, 'HU.png'),
(100, 'IS', 'Iceland', 354, 'IS.png'),
(101, 'IN', 'India', 91, 'IN.png'),
(102, 'ID', 'Indonesia', 62, 'ID.png'),
(103, 'IR', 'Iran', 98, 'IR.png'),
(104, 'IQ', 'Iraq', 964, 'IQ.png'),
(105, 'IE', 'Ireland', 353, 'IE.png'),
(106, 'IL', 'Israel', 972, 'IL.png'),
(107, 'IT', 'Italy', 39, 'IT.png'),
(108, 'JM', 'Jamaica', 1876, 'JM.png'),
(109, 'JP', 'Japan', 81, 'JP.png'),
(110, 'XJ', 'Jersey', 44, 'JE.png'),
(111, 'JO', 'Jordan', 962, 'JO.png'),
(112, 'KZ', 'Kazakhstan', 7, 'KZ.png'),
(113, 'KE', 'Kenya', 254, 'KE.png'),
(114, 'KI', 'Kiribati', 686, 'KI.png'),
(115, 'KP', 'Korea North', 850, NULL),
(116, 'KR', 'Korea South', 82, NULL),
(117, 'KW', 'Kuwait', 965, 'KW.png'),
(118, 'KG', 'Kyrgyzstan', 996, 'KG.png'),
(119, 'LA', 'Laos', 856, 'LA.png'),
(120, 'LV', 'Latvia', 371, 'LV.png'),
(121, 'LB', 'Lebanon', 961, 'LB.png'),
(122, 'LS', 'Lesotho', 266, 'LS.png'),
(123, 'LR', 'Liberia', 231, 'LR.png'),
(124, 'LY', 'Libya', 218, 'LY.png'),
(125, 'LI', 'Liechtenstein', 423, 'LI.png'),
(126, 'LT', 'Lithuania', 370, 'LT.png'),
(127, 'LU', 'Luxembourg', 352, 'LU.png'),
(128, 'MO', 'Macau S.A.R.', 853, NULL),
(129, 'MK', 'Macedonia', 389, 'MK.png'),
(130, 'MG', 'Madagascar', 261, 'MG.png'),
(131, 'MW', 'Malawi', 265, 'MW.png'),
(132, 'MY', 'Malaysia', 60, 'MY.png'),
(133, 'MV', 'Maldives', 960, 'MV.png'),
(134, 'ML', 'Mali', 223, 'ML.png'),
(135, 'MT', 'Malta', 356, 'MT.png'),
(136, 'XM', 'Man (Isle of)', 44, NULL),
(137, 'MH', 'Marshall Islands', 692, 'MH.png'),
(138, 'MQ', 'Martinique', 596, 'MQ.png'),
(139, 'MR', 'Mauritania', 222, 'MR.png'),
(140, 'MU', 'Mauritius', 230, 'MU.png'),
(141, 'YT', 'Mayotte', 269, 'YT.png'),
(142, 'MX', 'Mexico', 52, 'MX.png'),
(143, 'FM', 'Micronesia', 691, 'FM.png'),
(144, 'MD', 'Moldova', 373, 'MD.png'),
(145, 'MC', 'Monaco', 377, 'MC.png'),
(146, 'MN', 'Mongolia', 976, 'MN.png'),
(147, 'MS', 'Montserrat', 1664, 'MS.png'),
(148, 'MA', 'Morocco', 212, 'MA.png'),
(149, 'MZ', 'Mozambique', 258, 'MZ.png'),
(150, 'MM', 'Myanmar', 95, NULL),
(151, 'NA', 'Namibia', 264, 'NA.png'),
(152, 'NR', 'Nauru', 674, 'NR.png'),
(153, 'NP', 'Nepal', 977, 'NP.png'),
(154, 'AN', 'Netherlands Antilles', 599, NULL),
(155, 'NL', 'Netherlands The', 31, NULL),
(156, 'NC', 'New Caledonia', 687, 'NC.png'),
(157, 'NZ', 'New Zealand', 64, 'NZ.png'),
(158, 'NI', 'Nicaragua', 505, 'NI.png'),
(159, 'NE', 'Niger', 227, 'NE.png'),
(160, 'NG', 'Nigeria', 234, 'NG.png'),
(161, 'NU', 'Niue', 683, 'NU.png'),
(162, 'NF', 'Norfolk Island', 672, 'NF.png'),
(163, 'MP', 'Northern Mariana Islands', 1670, 'MP.png'),
(164, 'NO', 'Norway', 47, 'NO.png'),
(165, 'OM', 'Oman', 968, 'OM.png'),
(166, 'PK', 'Pakistan', 92, 'PK.png'),
(167, 'PW', 'Palau', 680, 'PW.png'),
(168, 'PS', 'Palestinian Territory Occupied', 970, NULL),
(169, 'PA', 'Panama', 507, 'PA.png'),
(170, 'PG', 'Papua new Guinea', 675, 'PG.png'),
(171, 'PY', 'Paraguay', 595, 'PY.png'),
(172, 'PE', 'Peru', 51, 'PE.png'),
(173, 'PH', 'Philippines', 63, 'PH.png'),
(174, 'PN', 'Pitcairn Island', 0, NULL),
(175, 'PL', 'Poland', 48, 'PL.png'),
(176, 'PT', 'Portugal', 351, 'PT.png'),
(177, 'PR', 'Puerto Rico', 1787, 'PR.png'),
(178, 'QA', 'Qatar', 974, 'QA.png'),
(179, 'RE', 'Reunion', 262, 'RE.png'),
(180, 'RO', 'Romania', 40, 'RO.png'),
(181, 'RU', 'Russia', 70, 'RU.png'),
(182, 'RW', 'Rwanda', 250, 'RW.png'),
(183, 'SH', 'Saint Helena', 290, 'SH.png'),
(184, 'KN', 'Saint Kitts And Nevis', 1869, 'KN.png'),
(185, 'LC', 'Saint Lucia', 1758, 'LC.png'),
(186, 'PM', 'Saint Pierre and Miquelon', 508, 'PM.png'),
(187, 'VC', 'Saint Vincent And The Grenadines', 1784, 'VC.png'),
(188, 'WS', 'Samoa', 684, 'WS.png'),
(189, 'SM', 'San Marino', 378, 'SM.png'),
(190, 'ST', 'Sao Tome and Principe', 239, 'ST.png'),
(191, 'SA', 'Saudi Arabia', 966, 'SA.png'),
(192, 'SN', 'Senegal', 221, 'SN.png'),
(193, 'RS', 'Serbia', 381, 'RS.png'),
(194, 'SC', 'Seychelles', 248, 'SC.png'),
(195, 'SL', 'Sierra Leone', 232, 'SL.png'),
(196, 'SG', 'Singapore', 65, 'SG.png'),
(197, 'SK', 'Slovakia', 421, 'SK.png'),
(198, 'SI', 'Slovenia', 386, 'SI.png'),
(199, 'XG', 'Smaller Territories of the UK', 44, NULL),
(200, 'SB', 'Solomon Islands', 677, 'SB.png'),
(201, 'SO', 'Somalia', 252, 'SO.png'),
(202, 'ZA', 'South Africa', 27, 'ZA.png'),
(203, 'GS', 'South Georgia', 0, NULL),
(204, 'SS', 'South Sudan', 211, 'SS.png'),
(205, 'ES', 'Spain', 34, 'ES.png'),
(206, 'LK', 'Sri Lanka', 94, 'LK.png'),
(207, 'SD', 'Sudan', 249, 'SD.png'),
(208, 'SR', 'Suriname', 597, 'SR.png'),
(209, 'SJ', 'Svalbard And Jan Mayen Islands', 47, NULL),
(210, 'SZ', 'Swaziland', 268, 'SZ.png'),
(211, 'SE', 'Sweden', 46, 'SE.png'),
(212, 'CH', 'Switzerland', 41, 'CH.png'),
(213, 'SY', 'Syria', 963, 'SY.png'),
(214, 'TW', 'Taiwan', 886, 'TW.png'),
(215, 'TJ', 'Tajikistan', 992, 'TJ.png'),
(216, 'TZ', 'Tanzania', 255, 'TZ.png'),
(217, 'TH', 'Thailand', 66, 'TH.png'),
(218, 'TG', 'Togo', 228, 'TG.png'),
(219, 'TK', 'Tokelau', 690, 'TK.png'),
(220, 'TO', 'Tonga', 676, 'TO.png'),
(221, 'TT', 'Trinidad And Tobago', 1868, 'TT.png'),
(222, 'TN', 'Tunisia', 216, 'TN.png'),
(223, 'TR', 'Turkey', 90, 'TR.png'),
(224, 'TM', 'Turkmenistan', 7370, 'TM.png'),
(225, 'TC', 'Turks And Caicos Islands', 1649, 'TC.png'),
(226, 'TV', 'Tuvalu', 688, 'TV.png'),
(227, 'UG', 'Uganda', 256, 'UG.png'),
(228, 'UA', 'Ukraine', 380, 'UA.png'),
(229, 'AE', 'United Arab Emirates', 971, 'AE.png'),
(230, 'GB', 'United Kingdom', 44, 'GB.png'),
(231, 'US', 'United States', 1, 'US.png'),
(232, 'UM', 'United States Minor Outlying Islands', 1, NULL),
(233, 'UY', 'Uruguay', 598, 'UY.png'),
(234, 'UZ', 'Uzbekistan', 998, 'UZ.png'),
(235, 'VU', 'Vanuatu', 678, 'VU.png'),
(236, 'VA', 'Vatican City State (Holy See)', 39, NULL),
(237, 'VE', 'Venezuela', 58, 'VE.png'),
(238, 'VN', 'Vietnam', 84, 'VN.png'),
(239, 'VG', 'Virgin Islands (British)', 1284, NULL),
(240, 'VI', 'Virgin Islands (US)', 1340, NULL),
(241, 'WF', 'Wallis And Futuna Islands', 681, NULL),
(242, 'EH', 'Western Sahara', 212, 'EH.png'),
(243, 'YE', 'Yemen', 967, 'YE.png'),
(244, 'YU', 'Yugoslavia', 38, NULL),
(245, 'ZM', 'Zambia', 260, 'ZM.png'),
(246, 'ZW', 'Zimbabwe', 263, 'ZW.png');

-- blood groups
INSERT INTO `blood_groups` (`id`, `name`, `created_at`, `updated_at`)
VALUES
(1, 'A+', NULL, NULL),
(2, 'A-', NULL, NULL),
(3, 'B+', NULL, NULL),
(4, 'B-', NULL, NULL),
(5, 'AB+', NULL, NULL),
(6, 'AB-', NULL, NULL),
(7, 'O+', NULL, NULL),
(8, 'O-', NULL, NULL);

-- dietary preferences
INSERT INTO `dietary_preferences` (`id`, `name`, `description`, `created_at`, `updated_at`)
VALUES
(1, 'Omnivore', 'Eats all types of food without dietary restrictions.', NULL, NULL),
(2, 'Vegetarian', 'Avoids meat, poultry, and seafood.', NULL, NULL),
(3, 'Vegan', 'Avoids all animal products including meat, dairy, eggs, and honey.', NULL, NULL),
(4, 'Pescatarian', 'Eats fish but avoids other meats.', NULL, NULL),
(5, 'Flexitarian', 'Mostly vegetarian but occasionally eats meat.', NULL, NULL),
(6, 'Pollotarian', 'Eats poultry but avoids red meat and seafood.', NULL, NULL),
(7, 'Halal', 'Follows Islamic dietary laws; avoids pork, alcohol, and non-halal meat.', NULL, NULL),
(8, 'Kosher', 'Follows Jewish dietary laws, including separation of meat and dairy.', NULL, NULL),
(9, 'Hindu Vegetarian', 'Avoids meat, especially beef, and sometimes eggs.', NULL, NULL),
(10, 'Jain Vegetarian', 'Strict vegetarian avoiding root vegetables and animal by-products.', NULL, NULL),
(11, 'Buddhist Vegetarian', 'Vegetarian diet, may avoid strong-flavored vegetables like garlic or onions.', NULL, NULL),
(12, 'Ital', 'Rastafarian natural diet emphasizing plant-based, unprocessed foods.', NULL, NULL),
(13, 'Gluten-free', 'Avoids foods containing gluten such as wheat, barley, and rye.', NULL, NULL),
(14, 'Dairy-free', 'Avoids milk and dairy products due to allergy or intolerance.', NULL, NULL),
(15, 'Nut-free', 'Avoids nuts and nut-based products.', NULL, NULL),
(16, 'Egg-free', 'Avoids eggs and egg-based products.', NULL, NULL),
(17, 'Soy-free', 'Avoids soy and soy-derived foods.', NULL, NULL),
(18, 'Low-FODMAP', 'Avoids fermentable carbohydrates to reduce digestive discomfort.', NULL, NULL),
(19, 'Keto', 'Follows a low-carbohydrate, high-fat ketogenic diet.', NULL, NULL),
(20, 'Paleo', 'Eats foods presumed available to early humans; excludes processed foods, grains, and dairy.', NULL, NULL),
(21, 'Raw Food', 'Consumes mostly raw, uncooked foods.', NULL, NULL),
(22, 'Macrobiotic', 'Plant-based diet emphasizing whole grains and seasonal foods.', NULL, NULL),
(23, 'Whole30', 'A 30-day elimination diet avoiding sugar, grains, dairy, and legumes.', NULL, NULL),
(24, 'Frugivore', 'Primarily eats fruits as main food source.', NULL, NULL),
(25, 'Medical / Therapeutic Diet', 'Diet prescribed for medical reasons such as low-sodium or diabetic diets.', NULL, NULL),
(26, 'No Preference', 'No specific dietary restrictions or preferences.', NULL, NULL),
(27, 'Other', 'Other or custom dietary preference not listed above.', NULL, NULL);


-- add room types
INSERT INTO `room_types`(`name`) VALUES
('Standard Room'),
('Superior Room'),
('Deluxe Room'),
('Premier Room'),
('Executive Room'),
('Family Room'),
('Triple Room'),
('Quad Room'),
('Junior Suite'),
('Executive Suite'),
('Family Suite'),
('Deluxe Suite'),
('Presidential Suite'),
('Cabana'),
('Chalet'),
('Villa Room'),
('Garden View Room'),
('Ocean View Room'),
('Mountain View Room'),
('Pool View Room');

-- add bed types
INSERT INTO `bed_types` (`name`) VALUES
('Single Bed'),
('Twin Beds'),
('Double Bed'),
('Queen Bed'),
('King Bed'),
('Super King Bed'),
('Bunk Bed'),
('Sofa Bed'),
('Extra Bed (Rollaway Bed)');

-- add boarding types
INSERT INTO `boarding_types`(`name`, `description`) VALUES
('Room Only', 'No meals included — just the room.'),
('Self-Catering', 'You cook your own meals; a kitchen is provided.'),
('Bed & Breakfast (B&B)', 'Breakfast included (usually buffet-style, sometimes à la carte in boutique or luxury hotels).'),
('Half Board', 'Breakfast + one main meal (usually dinner); drinks may not be included.'),
('Full Board', 'All three main meals included; drinks often cost extra.'),
('All-Inclusive', 'Meals, snacks, drinks (alcoholic too), and sometimes activities included.'),
('Ultra All-Inclusive', 'All of the above plus extras like 24/7 service, à la carte restaurants, and premium drinks.');

-- add meal types
INSERT INTO `meal_types`(`name`) VALUES
('Breakfast'),
('Lunch'),
('Dinner'),
('Snacks'),
('Brunch');

-- add Activity categories
INSERT INTO `activity_categories`(`name`) VALUES
('Adventure'),
('Cultural'),
('Wildlife'),
('Leisure');

-- add activity times
INSERT INTO `activity_times`(`name`) VALUES
('Morning'),
('Noon'),
('Evening'),
('Night'),
('Full Day');

-- add activity prices
INSERT INTO `activity_prices`(`name`) VALUES
('Per Person'),
('Per Group');

-- add currencies
INSERT INTO `currencies`(`name`) VALUES
('USD'),
('JPY'),
('LKR'),
('AED');

-- add tour purposes
INSERT INTO `tour_purposes`(`name`) VALUES
('Leisure / Holiday'),
('Honeymoon'),
('Family Vacation'),
('Friends Getaway'),
('Business Travel'),
('Cultural Tour'),
('Adventure Tour'),
('Wildlife / Safari'),
('Educational Tour'),
('Custom / Tailor-Made Tour');

-- add group composition
INSERT INTO `group_compositions`(`name`) VALUES
('Singles'),
('Couples'),
('Families'),
('Friends');

-- add tour packages
INSERT INTO `tour_packages`(`name`) VALUES
('Akagi Essential'),
('Akagi Classic'),
('Akagi Signature');

-- add price modes
INSERT INTO `price_modes`(`name`) VALUES
('Per Person'),
('Per Group'),
('Per Day'),
('Flat');

-- add hotel price modes
INSERT INTO `hotel_price_modes`(`name`) VALUES
('Extra Bed – Adult'),
('Extra Bed – Child'),
('Baby Cot / Crib'),
('Room Upgrade (Higher Category)'),
('Sea / City / Landmark View Upgrade'),
('Early Check-in'),
('Late Check-out'),
('Breakfast Supplement (BB)'),
('Half Board Supplement (HB)'),
('Full Board Supplement (FB)'),
('All Inclusive Supplement (AI)'),
('Tourism / City Tax'),
('Municipality / Local Fee'),
('Service Charge'),
('VAT / GST'),
('Resort Fee'),
('Spa / Wellness Access'),
('Pool / Beach Access'),
('Executive Lounge Access'),
('Complimentary Upgrade (Subject to Availability)'),
('Welcome Amenities (Fruits / Drinks)'),
('Express Check-in / Concierge Service'),
('Other');

-- add travel countries
INSERT INTO `travel_countries`(`name`) VALUES
('Sri Lanka'),
('Maldives');

-- add tour budgets table
INSERT INTO `tour_budgets`(`range`) VALUES
('1000$ - 5000$'),
('5000$ - 10000$'),
('10000$ - 20000$'),
('20000$ +');
